---
- name: Configure database server
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devops"
  roles:
    - default-config-so
    - role: geerlingguy.mysql