Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Building Docker Swarm cluster..."
    config.vm.define "manager" do |manager|
        manager.vm.box = "centos/7"
        manager.vm.hostname = "manager"
        manager.vm.provision "shell", path: "provision.sh"
        manager.vm.network "private_network", ip: "192.168.2.200"
        manager.vm.network "forwarded_port", guest: 80, host: 8090
    end
    config.vm.define "worker01" do |worker01|
        worker01.vm.box = "centos/7"
        worker01.vm.hostname = "worker01"
        worker01.vm.provision "shell", path: "provision.sh"
        worker01.vm.network "private_network", ip: "192.168.2.201"
    end
    config.vm.define "worker02" do |worker02|
        worker02.vm.box = "centos/7"
        worker02.vm.hostname = "worker02"
        worker02.vm.provision "shell", path: "provision.sh"
        worker02.vm.network "private_network", ip: "192.168.2.202"
    end
end